### ISSUE TITLE
covid-19のデータ項目変更

### ISSUE THREAD

**Issue by morimorijap** [mazarimono/notebook#1]
役に立つ記事をありがとうございました。
3章のcovid-19のデータ項目変更が変更されたようです。
年代:['30 ' '40 ' '60 ' '50 ' '20 ' '80 ' '70 ' '10 ' '0-10' '不明' '90 ' '100 ' '90以上']
のようになったようです、90以上の処理をどうするのが良さそうでしょうか？
アイデアをいただければ幸いです。

**Comment by mazarimono** [comment]
コメントありがとうございます。返信が遅くなり申し訳ございません。

今確認したところ、種類がissueを立てていただいた時点よりも増えているようです。

<a href="https://gyazo.com/e3cd8ef578217d98b45b88aea2567113"><img src="https://i.gyazo.com/e3cd8ef578217d98b45b88aea2567113.png" alt="Image from Gyazo" width="755.2"/></a>

応急処置的に、次のように同じような処理を加えてみました。
https://github.com/mazarimono/webdb_notebook/blob/master/chapter-3_colab.ipynb

<a href="https://gyazo.com/e93dfdea044eef476642de2f6e1a2f18"><img src="https://i.gyazo.com/e93dfdea044eef476642de2f6e1a2f18.png" alt="Image from Gyazo" width="788"/></a>

応急的できれいさがないので、もう少しきれいな処理も考えてみます。

**Comment by morimorijap** [comment]
ありがとうございます。参考にさせていただきます。
きれいな処理が考えられましたらまた教えていただければ幸いです。
